"""Shared constants and presentation helpers.

Colour system: the qualitative palette is the Okabe--Ito colourblind-safe set,
so hue is never the sole carrier of meaning for viewers with colour-vision
deficiency. Medal colours keep their semantic gold/silver/bronze identity but
are tuned to be luminance-distinct (bright -> mid -> dark), so they also read in
grayscale. Status uses one accent (green) against neutral gray "context" ink,
following the Big Book of Dashboards principle of colouring only what matters.
"""

from __future__ import annotations

import pandas as pd

# --- Okabe--Ito colourblind-safe qualitative palette ------------------------
OKABE = {
    "blue": "#0072B2",
    "orange": "#E69F00",
    "green": "#009E73",
    "vermillion": "#D55E00",
    "sky": "#56B4E9",
    "purple": "#CC79A7",
    "yellow": "#F0E442",
    "gray": "#7A8794",
}

# Brand ink / structure colours used by the dashboard chrome.
INK = "#1B2330"
MUTED = "#5B6675"
ACCENT = "#0072B2"

MEDAL_ORDER = ["Gold", "Silver", "Bronze"]

# Luminance-distinct so the stack reads in grayscale too.
MEDAL_COLORS = {
    "Gold": "#E3A81B",
    "Silver": "#9AA6B2",
    "Bronze": "#B5713B",
}

# One accent (green = "achieved") against neutral gray context ink.
STATUS_COLORS = {
    "Medalist": "#009E73",
    "No medal": "#AEB7C2",
}

# Most-distinct CVD-safe pair (orange vs blue).
GENDER_COLORS = {
    "Female": "#E69F00",
    "Male": "#0072B2",
}

# Sequential gray -> blue ramp: emphasis grows with the medal tier.
TIER_COLORS = {
    "No medals": "#D7DDE3",
    "1-9 medals": "#9DC3E0",
    "10-29 medals": "#4E95C9",
    "30+ medals": "#08519C",
}

# Diverging pair for gain/loss (CVD-safe).
POS_COLOR = "#009E73"
NEG_COLOR = "#D55E00"

# Categorical sequence for treemap / multi-series charts.
PALETTE = [
    "#0072B2",
    "#E69F00",
    "#009E73",
    "#D55E00",
    "#56B4E9",
    "#CC79A7",
    "#8C8C8C",
    "#117733",
]

# Sequential continuous scales (all CVD-safe / perceptually ordered).
SCALE_INTENSITY = "YlOrRd"   # medal "heat" on the world map
SCALE_BLUE = "Blues"         # specialization heatmap
SCALE_VENUE = "Viridis"      # venue medal activity
SCALE_RECORD = "Oranges"     # record counts


def style_plotly_chart(fig, height: int | None = None):
    """Apply one consistent, restrained visual style to Plotly figures."""
    fig.update_layout(
        template="plotly_white",
        font=dict(family="Inter, 'Segoe UI', Arial, sans-serif", size=13, color=INK),
        title=dict(
            font=dict(family="Inter, 'Segoe UI', Arial, sans-serif", size=16, color=INK),
            x=0.01,
            xanchor="left",
            y=0.97,
            yanchor="top",
        ),
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        margin=dict(l=46, r=28, t=58, b=44),
        legend=dict(
            orientation="h",
            yanchor="bottom",
            y=1.02,
            xanchor="right",
            x=1,
            bgcolor="rgba(255,255,255,0.0)",
            title_text="",
        ),
        colorway=PALETTE,
        hoverlabel=dict(bgcolor="white", font_size=12, font_family="Inter, Arial, sans-serif"),
    )
    fig.update_xaxes(
        showgrid=True,
        gridcolor="rgba(148,163,184,0.18)",
        zeroline=False,
        title_standoff=8,
        title_font=dict(size=12, color=MUTED),
        tickfont=dict(color=MUTED),
    )
    fig.update_yaxes(
        showgrid=True,
        gridcolor="rgba(148,163,184,0.18)",
        zeroline=False,
        title_standoff=8,
        title_font=dict(size=12, color=MUTED),
        tickfont=dict(color=MUTED),
    )
    if height:
        fig.update_layout(height=height)
    return fig


def format_number(value) -> str:
    """Format integer-like numbers for dashboard KPIs."""
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return "n/a"
    return f"{int(round(value)):,}"


def format_percent(value, decimals: int = 1) -> str:
    """Format a fraction as a percentage."""
    if value is None or pd.isna(value):
        return "n/a"
    return f"{value * 100:.{decimals}f}%"


def country_label(row: pd.Series) -> str:
    """Return sidebar-friendly country label."""
    return f"{row['code']} - {row['country']}"


def parse_country_codes(labels: list[str]) -> list[str]:
    """Parse NOC codes from labels generated by country_label."""
    return [label.split(" - ", 1)[0] for label in labels]
